name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
          lfs: true
    - name: set up JDK 
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.5" 
        validate-wrappers: false
        allow-snapshot-wrappers: true
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Build
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build
        path: /home/runner/work/gps4pets-android/gps4pets-android/app/build/outputs/apk/
